'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.whatIs': 'What is InstaPay?',
    'nav.howTo': 'How to?',
    'nav.login': 'Login',
    'nav.signUp': 'Sign Up',
    'nav.language': 'Language',
    'hero.slide1.title': 'Send money to anyone, anywhere, at any time!',
    'hero.slide1.desc': 'You can send money from your bank account or Meeza Prepaid card instantly 24/7 to any Bank Accounts, Digital Wallets and any Card.',
    'hero.slide2.title': 'Self-onboarding.',
    'hero.slide2.desc': 'No need to sign any papers, just onboard yourself digitally.',
    'hero.slide3.title': 'More than just payments.',
    'hero.slide3.desc': 'Experience a seamless way to manage your finances on the go.',
    'whatIs.title': 'What is InstaPay?',
    'whatIs.desc': 'InstaPay is an app that allows direct access to all your bank accounts and transfer instantly using your mobile device 24/7.',
    'whatIs.card1': 'Transaction Limits and Fees',
    'whatIs.card2': 'What Is IPA?',
    'whatIs.card3': 'How to receive money on your mobile number?',
    'whatIs.card4': 'What is the transaction status handling?',
    'whatIs.learnMore': 'Learn More',
    'howTo.title': 'How To ?',
    'howTo.category.send': 'Sending Money',
    'howTo.category.request': 'Request Money',
    'howTo.category.balance': 'Check Balance',
    'howTo.category.statement': 'Check Mini Statement',
    'howTo.category.addBank': 'Add Multiple Bank accounts',
    'howTo.item1': 'to an IPA (Instant Payment Address)',
    'howTo.item2': 'to a Digital Wallet',
    'howTo.item3': 'to a Bank Account',
    'howTo.item4': 'Transfer to any bank card',
    'howTo.item5': 'From other InstaPay users',
    'howTo.item6': 'Check Balance',
    'howTo.item7': 'Check Mini Statement',
    'howTo.item8': 'Add Multiple Bank accounts',
    'howTo.item9': 'through Mobile Number Only',
    'getStarted.title': 'Get Started',
    'getStarted.desc': 'Download InstaPay app now and enjoy the experience of instant payments.',
      'enabledBanks.title': 'Enabled Banks',
      'footer.rights': '© 2024 InstaPay. All rights reserved.',
      'login.security': 'MILITARY-GRADE SECURITY',
      'login.login': 'Login',
      'login.register': 'Register',
      'login.fullName': 'Full Name',
      'login.mobileNumber': 'Mobile Number',
      'login.password': 'Password',
      'login.processing': 'Processing...',
      'login.createAccount': 'Create Account',
      'login.fail': 'Identification failed',
      'login.success': 'Success! Accessing Secure Vault...',
      'login.accountCreated': 'Account Created Successfully!',
      'login.networkError': 'Network Error. Please try again.',
      'login.footer': '© 2025 InstaPay Egypt • Secure Session',
      'dash.welcome': 'Welcome back,',
      'dash.updating': 'Updating dashboard...',
      'dash.balance': 'Available Balance',
      'dash.send': 'Send Money',
      'dash.sendDesc': 'Instant transfer',
      'dash.collect': 'Collect Money',
      'dash.collectDesc': 'Request payment',
      'dash.accounts': 'Accounts',
      'dash.accountsDesc': 'Manage bank',
      'dash.bill': 'Bill Pay',
      'dash.billDesc': 'Utilities & more',
      'dash.activity': 'Recent Activity',
      'dash.viewAll': 'View All',
      'dash.noTrans': 'No transactions found.',
      'dash.from': 'From:',
      'dash.to': 'To:',
      'dash.logout': 'Logout',
      'dash.admin': 'Admin Panel',
      'send.title': 'Send Money Instantly',
      'send.desc': 'Transfer funds easily and securely to any InstaPay user.',
      'send.details': 'Transfer Details',
      'send.mobile': 'Recipient Mobile Number',
      'send.amount': 'Amount (EGP)',
      'send.confirm': 'Confirm & Send Now',
      'send.back': 'Back to Dashboard',
      'send.success': 'Transaction completed successfully!',
      'send.error.phone': 'Please enter a valid mobile number',
      'send.error.amount': 'Please enter a valid amount',
      'send.error.balance': 'Insufficient balance',
      'manage.title': 'Settings & Security',
      'manage.wallet': 'Wallet',
      'manage.security': 'Security',
      'manage.premium': 'Premium Member',
      'manage.linked': 'Linked Payment Account',
      'manage.cardType': 'INSTAPAY GOLD',
      'manage.fullName': 'Full Name',
      'manage.secUpdate': 'Security Update',
      'manage.currPass': 'Current Password',
      'manage.newPass': 'New Password',
      'manage.updatePass': 'Update Password',
      'manage.saving': 'Saving...',
      'manage.save': 'Save',
      'manage.updating': 'Updating...',
      'manage.picUpdated': 'Profile picture updated!',
      'manage.nameUpdated': 'Name updated successfully!',
      'manage.passUpdated': 'Password updated!',
      'bill.title': 'Pay Your Bills',
      'bill.desc': 'Fast, secure and instant utility payments.',
      'bill.details': 'Payment Details',
      'bill.electricity': 'Electricity',
      'bill.water': 'Water',
      'bill.mobile': 'Mobile',
      'bill.internet': 'Internet',
      'bill.meter': 'Meter / Account Number',
      'bill.payNow': 'Pay Now',
      'bill.history': 'Bill History',
      'bill.noBills': 'No bills yet',
      'bill.secTip': 'Security Tip',
        'bill.secTipDesc': 'Always verify the meter number before payment. Transactions cannot be reversed.',
        'bill.recordRemoved': 'Record removed from history',
        'bill.deleteFailed': 'Delete failed',
        'bill.connError': 'Connection error',
        'bill.fillFields': 'Please fill all fields',
        'bill.lowBalance': 'Insufficient balance!',
        'bill.paySuccess': 'Bill paid successfully!',
        'bill.payDeclined': 'Payment declined by server',
        'bill.success': 'Success',
        'bill.attention': 'Attention',
        'bill.removeActivity': 'Remove Activity',
        'bill.confirmDelete': 'Delete this bill record from your history?',
        'bill.cancel': 'Cancel',
        'bill.yesDelete': 'Yes, Delete',
        'bill.utilityBill': 'Utility Bill',
        'collect.title': 'Collect Money',
      'collect.instantly': 'Instantly.',
      'collect.desc': 'Request payments securely from any user using only their mobile number.',
      'collect.step1': 'Enter payer\'s phone number',
      'collect.step2': 'Set the amount you need',
      'collect.step3': 'Recipient receives notification',
      'collect.newReq': 'New Request',
      'collect.payerPhone': 'Payer Mobile Number',
      'collect.generate': 'Generate Request',
      'collect.success': 'Request Sent Successfully!',
      'admin.panel': 'Admin Control Panel',
      'admin.manageUsers': 'Manage Users',
      'admin.allActivity': 'All Activity',
      'admin.totalUsers': 'Total Users',
      'admin.totalPlatform': 'Total Platform Balance',
      'admin.totalTrans': 'Total Transactions',
      'admin.billsPaid': 'Bills Paid',
      'admin.summary': 'System-wide Transactions Summary',
      'admin.latest': 'Latest 5 Operations',
      'admin.party': 'Transaction Party',
      'admin.type': 'Type',
      'admin.time': 'Time',
        'admin.back': 'Back to App',
        'admin.trans.back': 'Back to Admin Dashboard',
        'admin.trans.logs': 'System Logs',
        'admin.trans.monitor': 'Monitoring all global transactions',
        'admin.trans.search': 'Search name, phone, or service...',
        'admin.trans.noRes': 'No results match your search.',
        'admin.trans.noAct': 'No system activity recorded yet.',
        'admin.trans.th.status': 'Status/Type',
        'admin.trans.th.sender': 'Sender Details',
        'admin.trans.th.details': 'Transaction Details',
        'admin.trans.th.amount': 'Amount',
        'admin.trans.th.date': 'Date',
        'admin.trans.to': 'To:',
        'admin.trans.standard': 'Standard Transfer',
        'admin.users.back': 'Back to Dashboard',
        'admin.users.title': 'User Management',
        'admin.users.search': 'Search...',
        'admin.users.th.user': 'User',
        'admin.users.th.phoneRole': 'Phone & Role',
        'admin.users.th.balance': 'Balance',
        'admin.users.th.actions': 'Actions',
        'admin.users.edit': 'Edit',
        'admin.users.delete': 'Delete',
        'admin.users.editTitle': 'Edit User',
        'admin.users.fullName': 'Full Name',
        'admin.users.phone': 'Phone Number',
        'admin.users.balance': 'Balance (EGP)',
        'admin.users.save': 'Save Changes',
        'admin.users.confirmDelete': 'Are you sure?',
        'admin.users.confirmDeleteDesc': 'You are about to delete this user. This cannot be undone!',
        'admin.users.yesDelete': 'Yes, delete it!',
        'admin.users.deleted': 'Deleted!',
        'admin.users.deletedDesc': 'User has been removed.',
        'admin.users.updated': 'Updated!',
        'admin.users.error': 'Error',
        'admin.users.fetchFail': 'Could not fetch users',
          'admin.users.serverFail': 'Server connection failed',
          'notif.title': 'Activity',
          'notif.newAlerts': 'You have {count} new alerts',
          'notif.noAlerts': 'No new notifications',
          'notif.loading': 'Loading activity...',
          'notif.empty': 'Your notification tray is empty',
          'notif.acceptPay': 'Accept & Pay',
          'notif.reject': 'Reject',
          'notif.processing': 'Processing...',
          'notif.completed': 'Transaction Completed',
          'notif.error.requestId': 'Request ID is missing!',
          'notif.error.server': 'Error connecting to server',
            'notif.dash': 'Dashboard',
              'dash.transfer': 'InstaPay Transfer',
              'type.transfer': 'Transfer',
              'type.bill': 'Bill',
              'notif.title.moneySent': 'Money Sent',
            'notif.title.paymentRequest': 'Payment Request',
            'notif.title.moneyReceived': 'Money Received',
            'notif.title.paymentReceived': 'Payment Received',
            'notif.desc.sentTo': 'Sent to {name}',
            'notif.desc.newReq': 'New money request received',
            'notif.desc.recvFrom': 'Received from {name}',
            'notif.desc.youRecv': 'You received a payment',
          },
          ar: {
        'nav.home': 'الرئيسية',

      'nav.whatIs': 'ما هو إنستا باي؟',
      'nav.howTo': 'كيف تستخدمه؟',
      'nav.login': 'تسجيل الدخول',
      'nav.signUp': 'إنشاء حساب',
      'nav.language': 'اللغة',
      'hero.slide1.title': 'أرسل أموالاً لأي شخص، في أي مكان، وفي أي وقت!',
      'hero.slide1.desc': 'يمكنك إرسال الأموال من حسابك البنكي أو بطاقة ميزة مسبقة الدفع فوراً 24/7 إلى أي حسابات بنكية، محافظ رقمية، أو أي بطاقة.',
      'hero.slide2.title': 'التسجيل الذاتي.',
      'hero.slide2.desc': 'لا حاجة للتوقيع على أي أوراق، فقط قم بالتسجيل بنفسك رقمياً.',
      'hero.slide3.title': 'أكثر من مجرد مدفوعات.',
      'hero.slide3.desc': 'استمتع بطريقة سلسة لإدارة أموالك أثناء التنقل.',
      'whatIs.title': 'ما هو إنستا باي؟',
      'whatIs.desc': 'إنستا باي هو تطبيق يتيح لك الوصول المباشر إلى جميع حساباتك البنكية والتحويل الفوري باستخدام جهازك المحمول على مدار الساعة طوال أيام الأسبوع.',
      'whatIs.card1': 'حدود المعاملات والرسوم',
      'whatIs.card2': 'ما هو عنوان الدفع اللحظي (IPA)؟',
      'whatIs.card3': 'كيف تستقبل الأموال عبر رقم هاتفك المحمول؟',
      'whatIs.card4': 'كيف يتم التعامل مع حالة المعاملة؟',
      'whatIs.learnMore': 'اعرف المزيد',
      'howTo.title': 'كيف تستخدمه؟',
      'howTo.category.send': 'إرسال الأموال',
      'howTo.category.request': 'طلب أموال',
      'howTo.category.balance': 'عرض الرصيد',
      'howTo.category.statement': 'عرض كشف حساب مختصر',
      'howTo.category.addBank': 'إضافة حسابات بنكية متعددة',
      'howTo.item1': 'إلى عنوان دفع لحظي (IPA)',
      'howTo.item2': 'إلى محفظة إلكترونية',
      'howTo.item3': 'إلى حساب بنكي',
      'howTo.item4': 'التحويل إلى أي بطاقة بنكية',
      'howTo.item5': 'من مستخدمي إنستا باي الآخرين',
      'howTo.item6': 'عرض الرصيد',
      'howTo.item7': 'عرض كشف حساب مختصر',
      'howTo.item8': 'إضافة حسابات بنكية متعددة',
      'howTo.item9': 'من خلال رقم الهاتف المحمول فقط',
      'getStarted.title': 'ابدأ الآن',
      'getStarted.desc': 'حمل تطبيق إنستا باي الآن واستمتع بتجربة المدفوعات اللحظية.',
      'enabledBanks.title': 'البنوك المشتركة',
      'footer.rights': '© 2024 إنستا باي. جميع الحقوق محفوظة.',
      'login.security': 'أمن بمستوى عسكري',
      'login.login': 'تسجيل الدخول',
      'login.register': 'تسجيل جديد',
      'login.fullName': 'الاسم الكامل',
      'login.mobileNumber': 'رقم الهاتف المحمول',
      'login.password': 'كلمة المرور',
      'login.processing': 'جاري المعالجة...',
      'login.createAccount': 'إنشاء حساب',
      'login.fail': 'فشل التحقق من الهوية',
      'login.success': 'نجاح! يتم الدخول إلى الخزنة الآمنة...',
      'login.accountCreated': 'تم إنشاء الحساب بنجاح!',
      'login.networkError': 'خطأ في الشبكة. يرجى المحاولة مرة أخرى.',
      'login.footer': '© 2025 إنستا باي مصر • جلسة آمنة',
      'dash.welcome': 'مرحباً بعودتك،',
      'dash.updating': 'جاري تحديث لوحة التحكم...',
      'dash.balance': 'الرصيد المتاح',
      'dash.send': 'إرسال أموال',
      'dash.sendDesc': 'تحويل فوري',
      'dash.collect': 'طلب أموال',
      'dash.collectDesc': 'طلب دفع',
      'dash.accounts': 'الحسابات',
      'dash.accountsDesc': 'إدارة الحسابات البنكية',
      'dash.bill': 'دفع الفواتير',
      'dash.billDesc': 'المرافق والمزيد',
      'dash.activity': 'النشاط الأخير',
      'dash.viewAll': 'عرض الكل',
      'dash.noTrans': 'لم يتم العثور على معاملات.',
      'dash.from': 'من:',
      'dash.to': 'إلى:',
      'dash.logout': 'تسجيل الخروج',
      'dash.admin': 'لوحة الإدارة',
      'send.title': 'أرسل أموالاً فوراً',
      'send.desc': 'حول الأموال بسهولة وأمان إلى أي مستخدم إنستا باي.',
      'send.details': 'تفاصيل التحويل',
      'send.mobile': 'رقم موبايل المستلم',
      'send.amount': 'المبلغ (جنيه مصري)',
      'send.confirm': 'تأكيد وإرسال الآن',
      'send.back': 'العودة للوحة التحكم',
      'send.success': 'تمت العملية بنجاح!',
      'send.error.phone': 'يرجى إدخال رقم هاتف صحيح',
      'send.error.amount': 'يرجى إدخال مبلغ صحيح',
      'send.error.balance': 'رصيدك الحالي لا يكفي لإتمام العملية',
      'manage.title': 'الإعدادات والأمان',
      'manage.wallet': 'المحفظة',
      'manage.security': 'الأمان',
      'manage.premium': 'عضو مميز',
      'manage.linked': 'حساب الدفع المرتبط',
      'manage.cardType': 'إنستا باي جولد',
      'manage.fullName': 'الاسم الكامل',
      'manage.secUpdate': 'تحديث الأمان',
      'manage.currPass': 'كلمة المرور الحالية',
      'manage.newPass': 'كلمة المرور الجديدة',
      'manage.updatePass': 'تحديث كلمة المرور',
      'manage.saving': 'جاري الحفظ...',
      'manage.save': 'حفظ',
      'manage.updating': 'جاري التحديث...',
      'manage.picUpdated': 'تم تحديث صورة الملف الشخصي!',
      'manage.nameUpdated': 'تم تحديث الاسم بنجاح!',
      'manage.passUpdated': 'تم تحديث كلمة المرور!',
      'bill.title': 'ادفع فواتيرك',
      'bill.desc': 'مدفوعات مرافق سريعة وآمنة وفورية.',
      'bill.details': 'تفاصيل الدفع',
      'bill.electricity': 'الكهرباء',
      'bill.water': 'المياه',
      'bill.mobile': 'الموبايل',
      'bill.internet': 'الإنترنت',
      'bill.meter': 'رقم العداد / الحساب',
      'bill.payNow': 'ادفع الآن',
      'bill.history': 'سجل الفواتير',
      'bill.noBills': 'لا توجد فواتير بعد',
      'bill.secTip': 'نصيحة أمنية',
      
        'bill.secTipDesc': 'تحقق دائماً من رقم العداد قبل الدفع. لا يمكن التراجع عن المعاملات.',
        'bill.recordRemoved': 'تمت إزالة السجل من المحفوظات',
        'bill.deleteFailed': 'فشل الحذف',
        'bill.connError': 'خطأ في الاتصال',
        'bill.fillFields': 'يرجى ملء جميع الحقول',
        'bill.lowBalance': 'الرصيد غير كافٍ!',
        'bill.paySuccess': 'تم دفع الفاتورة بنجاح!',
        'bill.payDeclined': 'تم رفض الدفع من قبل الخادم',
        'bill.success': 'نجاح',
        'bill.attention': 'تنبيه',
        'bill.removeActivity': 'إزالة النشاط',
        'bill.confirmDelete': 'هل تريد حذف سجل الفاتورة هذا من المحفوظات؟',
        'bill.cancel': 'إلغاء',
        'bill.yesDelete': 'نعم، احذف',
        'bill.utilityBill': 'فاتورة مرافق',
        'collect.title': 'اجمع الأموال',
      'collect.instantly': 'فوراً.',
      'collect.desc': 'اطلب المدفوعات بأمان من أي مستخدم باستخدام رقم هاتفه المحمول فقط.',
      'collect.step1': 'أدخل رقم هاتف الدافع',
      'collect.step2': 'حدد المبلغ الذي تحتاجه',
      'collect.step3': 'يتلقى المستلم إشعاراً',
      'collect.newReq': 'طلب جديد',
      'collect.payerPhone': 'رقم موبايل الدافع',
      'collect.generate': 'إنشاء الطلب',
      'collect.success': 'تم إرسال الطلب بنجاح!',
      'admin.panel': 'لوحة تحكم المسؤول',
      'admin.manageUsers': 'إدارة المستخدمين',
      'admin.allActivity': 'كل الأنشطة',
      'admin.totalUsers': 'إجمالي المستخدمين',
      'admin.totalPlatform': 'إجمالي رصيد المنصة',
      'admin.totalTrans': 'إجمالي المعاملات',
      'admin.billsPaid': 'الفواتير المدفوعة',
      'admin.summary': 'ملخص المعاملات على مستوى النظام',
      'admin.latest': 'آخر 5 عمليات',
      'admin.party': 'طرف المعاملة',
      'admin.type': 'النوع',
      'admin.time': 'الوقت',
        'admin.back': 'العودة للتطبيق',
        'admin.trans.back': 'العودة للوحة تحكم المسؤول',
        'admin.trans.logs': 'سجلات النظام',
        'admin.trans.monitor': 'مراقبة جميع المعاملات العالمية',
        'admin.trans.search': 'بحث بالاسم، الهاتف، أو الخدمة...',
        'admin.trans.noRes': 'لا توجد نتائج تطابق بحثك.',
        'admin.trans.noAct': 'لم يتم تسجيل أي نشاط للنظام بعد.',
        'admin.trans.th.status': 'الحالة/النوع',
        'admin.trans.th.sender': 'تفاصيل المرسل',
        'admin.trans.th.details': 'تفاصيل المعاملة',
        'admin.trans.th.amount': 'المبلغ',
        'admin.trans.th.date': 'التاريخ',
        'admin.trans.to': 'إلى:',
        'admin.trans.standard': 'تحويل عادي',
        'admin.users.back': 'العودة للوحة التحكم',
        'admin.users.title': 'إدارة المستخدمين',
        'admin.users.search': 'بحث...',
        'admin.users.th.user': 'المستخدم',
        'admin.users.th.phoneRole': 'الهاتف والدور',
        'admin.users.th.balance': 'الرصيد',
        'admin.users.th.actions': 'الإجراءات',
        'admin.users.edit': 'تعديل',
        'admin.users.delete': 'حذف',
        'admin.users.editTitle': 'تعديل مستخدم',
        'admin.users.fullName': 'الاسم بالكامل',
        'admin.users.phone': 'رقم الهاتف',
        'admin.users.balance': 'الرصيد (ج.م)',
        'admin.users.save': 'حفظ التغييرات',
        'admin.users.confirmDelete': 'هل أنت متأكد؟',
        'admin.users.confirmDeleteDesc': 'أنت على وشك حذف هذا المستخدم. لا يمكن التراجع عن هذا الإجراء!',
        'admin.users.yesDelete': 'نعم، احذفه!',
        'admin.users.deleted': 'تم الحذف!',
        'admin.users.deletedDesc': 'تمت إزالة المستخدم.',
        'admin.users.updated': 'تم التحديث!',
        'admin.users.error': 'خطأ',
        'admin.users.fetchFail': 'تعذر جلب المستخدمين',
          'admin.users.serverFail': 'فشل الاتصال بالخادم',
          'notif.title': 'النشاط',
          'notif.newAlerts': 'لديك {count} تنبيهات جديدة',
          'notif.noAlerts': 'لا توجد إشعارات جديدة',
          'notif.loading': 'جاري تحميل النشاط...',
          'notif.empty': 'سجل التنبيهات فارغ',
          'notif.acceptPay': 'قبول ودفع',
          'notif.reject': 'رفض',
          'notif.processing': 'جاري المعالجة...',
          'notif.completed': 'تمت العملية بنجاح',
          'notif.error.requestId': 'معرف الطلب مفقود!',
              'notif.error.server': 'خطأ في الاتصال بالخادم',
              'notif.dash': 'لوحة التحكم',
              'dash.transfer': 'تحويل إنستا باي',
              'type.transfer': 'تحويل',
              'type.bill': 'فاتورة',
              'notif.title.moneySent': 'تم إرسال أموال',
            'notif.title.paymentRequest': 'طلب دفع',
            'notif.title.moneyReceived': 'تم استلام أموال',
            'notif.title.paymentReceived': 'تم استلام الدفع',
            'notif.desc.sentTo': 'أُرسلت إلى {name}',
            'notif.desc.newReq': 'تم استلام طلب دفع جديد',
            'notif.desc.recvFrom': 'استلمت من {name}',
            'notif.desc.youRecv': 'لقد استلمت دفعة',
          },
        };


export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
